version: '3.4'
 
services:
 
  postgresql_database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=amdin
      - POSTGRES_PASSWORD=bQ8tbngMRVrJEf9d
      - POSTGRES_DB=weatherforecasts
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
     
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=amdin@forecasts.com
      - PGADMIN_DEFAULT_PASSWORD=aski1029
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
 
volumes:
  database-data:
  pgadmin: